[package]
name = "quadify"
repository = "https://github.com/StepanTheGreat/quadify"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Bevy plugin that integrates macroquad's windowing/rendering/sound API"
keywords = ["bevy", "macroquad", "miniquad"]
categories = ["game-engines"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version="0.12.0", default-features=false}
macroquad = "0.4.5"
